### ISSUE TITLE
[Fix] 일부 로직 수정

### ISSUE THREAD

**Issue by yh-project** [99z-diary/99z-diary-be-v2#16]
## 📔 Description
- 일부 로직의 수정이 필요

## 🐈 Todo
- [x] ~~쿠키 유효 인증 시 유저 정보 반환으로 수정~~ -> 기존 방식 유지
- [x] 쿠키로 사용자 정보 조회 구현
- [x] 스웨거 에러 description 수정
